main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('home/', home, name='home'),
    path('about/', about, name='about'),
    path('mission/', mission, name='mission'),
    path('contact/', contact, name='contact'),
    path('blog/', blog, name='blog'),
    path('blog_detail/<int:pk>/', blog_details, name='blog_detail'),
    path('media/', media_list, name='media'),
    path('contestant/', create_contestant, name='contestant'),
    path('song_list/', song_list, name='song_list'),
    path('song/<int:pk>/', song_detail, name='song_detail'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),
]

missdnk/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('main/', include('main.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.dispatch import receiver
from django.db import models
from django.utils import *


class About(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=5000, blank=False)

    def __str__(self):
        return self.title
    
    
class Mission(models.Model):
    title = models.CharField(max_length=100)
    mission_content = models.TextField(max_length=5000, blank=False)

    def __str__(self):
        return self.title
    

class HeaderImage(models.Model):
    POSITION_CHOICES = [
        ('First', 'First'),
        ('First Runners up', 'First Runners up'),
        ('Second Runners Up', 'Second Runners Up'),
    ]
    
    name = models.CharField(max_length=100, blank=False, default='Winner')
    year = models.IntegerField(default=2024)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES, default='First')
    image = models.ImageField(upload_to='header_images/', null=True, blank=True)

    def __str__(self):
        return f'{self.name}: {self.year} - {self.position}'

class UploadVideo(models.Model):
    title = models.CharField(max_length=50,null=False, default='Trending Videos')
    description = models.TextField(blank=True)
    video_title = models.FileField(upload_to='videos/', default='Trending Videos')
    upload_time = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.title
    
    @property
    def short_upload_time(self):
        return self.upload_time.strftime('%b %d, %Y %H:%M')


class NewsCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name
    

class Post(models.Model):
    category = models.ManyToManyField(NewsCategory)
    image = models.ImageField(upload_to='blog_images/', null=True, blank=True)
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post-details', args=[str(self.id)])
    

class UserFeedBack(models.Model):
    post = models.OneToOneField('Post', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    feedback = models.TextField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.send_notification()

    def send_notification(self):
        try:
            subject ='New User FeedBack Submission'
            message = f'A new feedback has been submitted:\n\nNmae: {self.mame}\nEmail: {self.email}\nFeedback: {self.feedback}'
        except Exception as e:
            print(f"Error sending notification: {e}")

    def __str__(self):
        return f'Feedback for {self.post.title} \n By {self.name}'

class RegistrationStatus(models.Model):
    is_registration_open = models.BooleanField(default=False)

    def __str__(self):
        return f"Registration is {'Open' if self.is_registration_open else 'Closed'}"

class Contestant(models.Model):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]

    full_name = models.CharField(max_length=150)
    stage_name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    phone_number = models.IntegerField(blank=False, default=2335834637)
    email = models.EmailField(default='missdnk@gmail.com')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Female')
    image = models.ImageField(upload_to='media', null=False, unique=True, blank=False)
    town = models.CharField(max_length=150)
    occupation = models.CharField(max_length=150)
    role_model = models.CharField(max_length=50)
    hobby = models.CharField(max_length=255)
    favourite_food = models.CharField(max_length=150)
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_year = models.IntegerField(default=timezone.now().year)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        super().save(*args, **kwargs)

    def clean(self):
        super().clean()
        if self.age > 35:
            raise ValidationError("Contestants must be 35 years or younger to register.")
    
        if self.gender in ['Male', 'Other']:
                raise ValidationError("Male's are not allowed to register for this contest.")

    def __str__(self):
        return self.full_name
    
class Pageant(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    date = models.DateField()
    location = models.CharField(max_length=255)
    contestants = models.ManyToManyField(Contestant)

    def __str__(self):
        return f"{self.id}: {self.name}"
    

class ContactUs(models.Model):
    full_name = models.CharField(max_length=100, blank=False)
    email = models.EmailField(blank=False)
    message = models.TextField(max_length=500, blank=False)

    def __str__(self):
        return self.full_name
    
class ContactPage(models.Model):
    email = models.EmailField()
    location = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    address = models.TextField()
    facebook_url = models.URLField(blank=True, null=True)
    twitter_handle = models.CharField(max_length=50, blank=True, null=True)
    instagram_handle = models.CharField(max_length=50, blank=True, null=True)
    tiktok_handle = models.CharField(max_length=50, blank=True, null=True)
    youtube_channel = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return "Contact Page"


class Song(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    audio_file = models.FileField(upload_to='audio_files/')
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

main/forms.py
from typing import Any
from django import forms
from .models import Contestant, Pageant, ContactUs, UserFeedBack, RegistrationStatus

class ContestantForm(forms.ModelForm):
    class Meta:
        model = Contestant
        fields = '__all__'
        exclude = ['approved']


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = '__all__'


class RegistrationStatusForm(forms.ModelForm):
    class Meta:
        model = RegistrationStatus
        fields = ['is_registration_open']

class UserFeedBackForm(forms.ModelForm):
    class Meta:
        model = UserFeedBack
        fields = ['name', 'email', 'feedback']

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        feedback = cleaned_data.get('feedback')

        if not name or not email or not feedback:
            raise forms.ValidationError('All fields are required.')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from .models import *
from .forms import ContestantForm, ContactUsForm, UserFeedBackForm


def home(request):
    current_year = timezone.now().year
    next_year = current_year + 1
    contestants = Contestant.objects.filter(approved=True)

    header_image = Header.objects.filter().first()

    registration_status = RegistrationStatus.objects.first()
    if registration_status:
        registration_open = registration_status.is_registration_open
    else:
        registration_open = False  # Set a default value if RegistrationStatus is not found

    context = {
        'contestants': contestants,
        'next_year': next_year,
    }
    return render(request, 'main/index.html', {'header_image': header_image, 'registration_open': registration_open, 'context': context})


def about(request):
    about_info = About.objects.first()
    return render(request, 'main/about.html', {'about_info': about_info})

def mission(request):
    mission_info = Mission.objects.first()
    return render(request, 'main/mission.html', {'mission_info': mission_info})

def contact(request):
    contact_update = ContactPage.objects.first()

    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = ContactUsForm()

    return render(request, 'main/contact.html', {'contact_update': contact_update, 'form': form})

def blog(request):
    posts = Post.objects.all()
    return render(request, 'main/blog.html', {'posts': posts})

def blog_details(request, pk):
    post = get_object_or_404(Post, id=pk)

    if request.method == 'POST':
        form = UserFeedBackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.post = post
            feedback.save()
            return redirect('main:blog_detail', pk=pk)
    else:
        form = UserFeedBackForm()

    return render(request, 'main/blog_detail.html', {'form': form, 'post': post})


class BlogDetailView(DetailView):
    model = Post
    template_name = 'main/post_detail.html'
    context_object_name = 'blog'


def media_list(request):
    media_items = UploadVideo.objects.all()
    return render(request, 'main/media.html', {'media_items': media_items})

# Contestant registration Form
def create_contestant(request):
    # Check if registration is open
    registration_status = RegistrationStatus.objects.first()

    if registration_status and hasattr(registration_status, 'is_registration_open'):
        registration_open = registration_status.is_registration_open
    else:
        registration_open = False  # Set a default value when registration_status or is_registration_open is None

    if not registration_open:
        return render(request, 'main/registration_closed.html')

    if request.method == 'POST':
        form = ContestantForm(request.POST, request.FILES)
        if form.is_valid():
            contestant_instance = form.save()
            send_admin_email(contestant_instance)
            return redirect('thank_you')
    else:
        form = ContestantForm()

    return render(request, 'main/contestant.html', {'form': form})

def send_admin_email(contestant_instance):
    subject = 'New Contestant Registration'
    message = f'A new contestant has registered.\n\nName: {contestant_instance.full_name}\nPhone Number: {contestant_instance.phone_number}'
    from_email = settings.DEFAULT_FROM_EMAIL
    recipient_list = ['missdnk@gmail.com']
    send_mail(subject, message, from_email, recipient_list)

def send_contestant_approval_email(contestant_instance):
    subject = 'Your Contestant Registration is Approved'
    message = f'Dear {contestant_instance.full_name},\n\nCongratulations! Your registration has been approved.'
    from_email = settings.DEFAULT_FROM_EMAIL
    recipient = [contestant_instance.email]
    send_mail(subject, message, from_email, recipient)

def song_list(request):
    songs = Song.objects.all()
    return render(request, 'main/song_list.html', {'songs': songs})

def song_detail(request, pk):
    song = get_object_or_404(Song, pk=pk)
    return render(request, 'main/song_detail.html', {'song': song})

# def download_song(request, pk):
#     song = get_object_or_404(Song, pk=pk)
#     response = FileResponse(song.audio_file)
#     return response

main/templates/main/about.html
{% extends "main/base.html" %}
{% block title %}About{% endblock %}
{% block content %}
{% load static %}

<main>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="about-section">
                    <h2>{{ about_info.title }}</h2>
                    <p>{{ about_info.content }}</p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"> -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'js/scripts.js' %}">
        <link rel="icon" href="data:,">
    </head>

    <body>
        <div class="top-navbar">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'main:contestant' %}" style="margin-left: 0;">
                        <img src="{% static 'logo/missdnk.jpg' %}" width="50" height="50" class="d-inline-block align-top" alt="">Miss Nkwanta
                    </a> 
                    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>                
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:song_list' %}">Latest Songs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:media' %}">Videos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:blog' %}">Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:about' %}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:mission' %}">Mission</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        

        <main>
            {% block content %} {% endblock %}
        </main>

        <script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script>
        <script src="{% static 'js/scripts.js'%}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script src="https://kit.fontawesome.com/00c9c1e1b6.js" crossorigin="anonymous"></script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        
    </body>
    <div id="content4">
    <div class="footer">
        <div class="contain">
            <div class="col social">
                <h1>Follow us</h1>
                <ul>
                    <a href=""><li><i class="fab fa-facebook"></i></li></a>
                    <a href=""><li><i class="fab fa-whatsapp"></i></li></a>
                    <a href=""><li><i class="fab fa-instagram"></i></li></a>
                    <a href=""><li><i class="fab fa-tiktok"></i></li></a>
                </ul>
            </div>
        </div>
    </div>
    
        <div class="footer-bottom">
            <p>&copy; 2016 miss DNK. All Rights Reserved.</p>
        </div>
    </div>
    
</html>

main/templates/main/blog.html
{% extends "main/base.html" %}
{% block title %}Blog{% endblock %}
{% block content %}
{% load static %}

<main>
    <div class="container mt-5">
        <div class="row">
            {% for blog in posts %}
                <div class="col-md-6 mb-4">
                    <div class="card">
                        {% if blog.image %}
                            <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                        {% endif %}
                        <div class="card-body">
                            <h2 class="card-title">{{ blog.title }}</h2>
                            <div class="categories">
                                <p>Categories:</p>
                                {% for category in blog.category.all %}
                                    <span>{{ category.name }}</span>
                                {% endfor %}
                            </div>
                            <p class="card-text">{{ blog.content | truncatewords:20 }}</p>
                            <a href="{% url 'main:blog_detail' pk=blog.pk %}" class="btn btn-success">Read more</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock %}

main/templates/main/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<main>
    <div class="bdcontainer mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-center mb-4">{{ post.title }}</h2>
                        <p>{{ post.content }}</p>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h2 class="text-center mb-4">User Feedback</h2>
                        <form method="post" action="{% url 'main:blog_detail' pk=post.id %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
                                {{ form.name }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                                {{ form.email }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ form.feedback.id_for_label }}" class="form-label">Feedback</label>
                                {{ form.feedback }}
                            </div>
                            <button type="submit" class="btn btn-success">Submit Feedback</button>
                        </form>
    
                        {% if form.errors %}
                            <div class="alert alert-danger mt-3">
                                {{ form.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</main>

{% endblock %}

main/templates/main/contact.html
{% extends "main/base.html" %}
{% block title %}Contact{% endblock %}
{% block content %}
{% load static %}

<main>
<section class="contact-page-sec">
  <div class="container">
    <div class="row">

      <div class="col-md-4">
        <div class="contact-info">
          <div class="contact-info-item">
            <div class="contact-info-icon">
              <i class="fas fa-map-marked"></i>
            </div>
            <div class="contact-info-text">
              <h2>Phone Number</h2>
              {% for phone in contact_update %}
                <span>{{ phone }}</span> 
              {% endfor %}
            </div>
          </div>            
        </div>          
      </div>  

      <div class="col-md-4">
        <div class="contact-info">
          <div class="contact-info-item">
            <div class="contact-info-icon">
              <i class="fas fa-envelope"></i>
            </div>
            <div class="contact-info-text">
              <h2>E-mail Address </h2>
              {% for email in contact_update %}
                <span>{{ email }}</span>
              {% endfor %}
            </div>
          </div>            
        </div>                
      </div>

      <div class="col-md-4">
        <div class="contact-info">
          <div class="contact-info-item">
            <div class="contact-info-icon">
              <i class="fas fa-map-marked"></i>
            </div>
            <div class="contact-info-text">
              <h2>Address </h2>
              <span>{{ contact_update.address }}</span> 
              <span>{{ contact_update.location }}</span> 
              <span>Donkro Nkwanta, Ghana</span> 
            </div>
          </div>            
        </div>          
      </div>                    
    <!-- Social Media Handles -->
    <div class="middle">
      {% if contact_update.facebook_url %}
      <a href="{{ contact_update.facebook_url }}" class="social-btn">
        <i class="fab fa-facebook-f"></i>
      </a>
      {% endif %}

      {% if contact_update.tiktok_handle %}
      <a href="{{ contact_update.tiktok_handle }}" class="social-btn">
        <i class="fa-brands fa-tiktok"></i>
      </a>
      {% endif %}
    
      {% if contact_update.twitter_handle %}
      <a href="https://twitter.com/{{ contact_update.twitter_handle }}" class="social-btn">
        <i class="fab fa-twitter"></i>
      </a>
      {% endif %}
    
      {% if contact_update.instagram_handle %}
      <a href="https://www.instagram.com/{{ contact_update.instagram_handle }}" class="social-btn">
        <i class="fab fa-instagram"></i>
      </a>
      {% endif %}
    
      {% if contact_update.youtube_channel %}
        <a href="{{ contact_update.youtube_channel }}" class="social-btn">
          <i class="fa-brands fa-youtube"></i>
        </a>
      {% endif %}
    </div>

    <div class="container">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="contact-page-form text-center">
                  <h2>Get in Touch</h2>
                  <form action="contact-mail" method="post">
                      <div class="row">
                          <div class="col-md-6 col-sm-6 col-xs-12 mx-auto">
                              <form method="post">
                                  {% csrf_token %}
                                  {{ form.as_p }}
                                  <button type="submit" class="btn btn-primary">Submit</button>
                              </form>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
  </div>
  </div>
</section>
</main>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
{% load static %}

<main>
<div id="carouselExampleCaptions" class="carousel slide mb-5" data-ride="carousel" style="height: 500px;">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
    </ol>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'logo/missdnk.jpg' %}" class="d-block w-100" alt="" height="500px">
        </div>

        <div class="carousel-item">
            <img src="{{ header_image.winner.url }}" class="d-block w-100" alt="Image not found" height="500px">
            <div class="carousel-caption d-none d-md-block text-dark">
                <h1>Winner</h1>
            </div>
        </div>
        
        <div class="carousel-item">
            <img src="{{ header_image.first_up.url }}" class="d-block w-100" alt="Image not found" height="500px">
            <div class="carousel-caption d-none d-md-block text-dark">
                <h2>1st Runner up</h2>
            </div>
        </div>
        
        <div class="carousel-item">
            <img src="{{ header_image.second_runner_up.url }}" class="d-block w-100" alt="Image not found" height="500px">
            <div class="carousel-caption d-none d-md-block text-dark">
                <h2>2nd Runner up</h2>
            </div>
        </div>
        
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container">
    <div class="contestant">
        <div class="row">
            <div class="col text-center">
                {% if registration_open %}
                    <h2 class="mb-4">Registration open for {{ context.next_year }}</h2>
                    <a href="{% url 'main:contestant' %}">
                        <button class="btn btn-success">Register</button>
                    </a>
                    <h3>Compete with others</h3>
                {% else %}
                    <h2 class="mb-4">Registration closed for {{ context.next_year }}.</h2>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% if contestants %}
            <h2 class="contest-year">{{ context.next_year }} Contestants</h2>
            <div class="contestants">
                {% for contestant in contestants %}
                    {% if contestant.approved and contestant.created_year == context.next_year %}
                        <div class="col-md-4 mb-4">
                            <div class="contestant text-center">
                                <img src="{{ contestant.image.url }}" alt="{{ contestant.full_name }}" class="img-fluid rounded-circle mb-3" style="max-width: 150px;">
                                <h2>{{ contestant.full_name }}</h2>
                                <p>Stage Name: {{ contestant.stage_name }}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <h2 class="mb-4">No Contestant for {{ context.next_year }}.</h2>
        {% endif %}
    </div>
</div>

</main>

{% endblock %}

main/templates/main/media.html
{% extends "main/base.html" %}
{% block title %}Media{% endblock %}
{% block content %}
{% load static %}

<main>
  <div class="video-container mt-5">
      <h2 class="mb-4">Media List</h2>
      <div class="row">
          {% for media in media_items %}
              <div class="col-md-4 mb-4">
                  <div class="card">
                      <div class="card-body">
                          <h5 class="card-title">{{ media.title }}</h5>
                          <p class="card-text">{{ media.description }}</p>
                          <video width="100%" height="auto" controls>
                            <source src="{{ media.video_title.url }}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                          <p class="mt-2">Uploaded on {{ media.upload_time }}</p>
                      </div>
                  </div>
              </div>
          {% endfor %}
      </div>
  </div>
</main>

  {% endblock %}

main/templates/main/mission.html
{% extends "main/base.html" %}
{% block title %}Mission{% endblock %}
{% block content %}
{% load static %}
<main>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 col-12 offset-lg-2 offset-md-1">
                <div class="about-section">
                    <h2>{{ about_info.title }}</h2>
                    <p>{{ about_info.content }}</p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

main/templates/main/registration_closed.html
{% extends 'main/base.html' %}
{% block content %}
<!-- {% block title %} Registration closed {% endblock %} -->
{% load static %}

<main>
    <div class="closd-container">
        <img src="{% static 'images/registration/reg_closed.png' %}" alt="Registration Closed Image">
        <h1>Registration Closed</h1>
        <p>We're sorry, but the registration is currently closed.</p>
        <p> See you next year</p>
    </div>
</main>

{% endblock %}